Version 1/171220 of Ailihphilia Tables by Andrew Schultz begins here.

volume random names of people and places

[use dbh.py to generate debug table version of this file]

chapter random names

[NOTE: can-m + can-f = a unisex name. False/False should never happen.]
table of random authors
person-name	can-m	can-f
"Eliza Bazile"	false	true
"Kera Marek"	false	true
"Leta Patel"	false	true
"Marge Pegram"	false	true
"Mika Hakim"	false	true
"Norma Damron"	false	true
"Reiko Kier"	false	true
"Rhea Baehr"	false	true
"Signe Kengis"	false	true
"Blake DeKalb"	true	true
"Leigh Giel"	true	true
"Adam Imada"	true	false
"Eldon Odle"	true	false
"Elias Osaile"	true	false
"Emory Rome"	true	false
"Gino Konig"	true	false
"Levi Rivel"	true	false
"Mark Cockram"	true	false
"Neil Klien"	true	false

table of random palindrome firstlast names
person-name
"Abe Keba"
"Agnus Unga"
"Alena Panela"
"Ali Vila"
"Alina Manila"
"Alona Zanola"
"Ami Cima"
"Amy Ma"
"Anika Kina"
"Anitra Martina"
"Annalee Lanna"
"Anne Kenna"
"Annika Kinna"
"Anya Rayna"
"Asa Casa"
"Ava Lava"
"Azalee Laza"
"Bernie Weinreb"
"Bert Streb"
"Betsey Esteb"
"Blake Kalb"
"Breana Erb"
"Breanna Erb"
"Bret Erb"
"Bruce Curb"
"Burt Strub"
"Cami Mac"
"Cassie Issac"
"Daisy Siad"
"Dara Jarad"
"Dee Reed"
"Denese Ned"
"Dian Aid"
"Diann Aid"
"Dorene Rod"
"Dori Girod"
"Duane Renaud"
"Ed Larralde"
"Ed Lazalde"
"Edie Weide"
"Edna Lalande"
"Edra Garde"
"Ela Bale"
"Ela Cicale"
"Ela Dale"
"Ela Yale"
"Elana Canale"
"Elda Wadle"
"Eli Kile"
"Elida Nadile"
"Elisa Basile"
"Ella Malle"
"Ellena Fanelle"
"Elli Tille"
"Elly Hylle"
"Elsie Isle"
"Elva Mavle"
"Emiko Kime"
"Emil Glime"
"Emily Lime"
"Emma Hamme"
"Emmitt Imme"
"Emmitt Timme"
"Ena Lane"
"Ena Sayasane"
"Enoch Cone"
"Enola Malone"
"Essie Heisse"
"Essie Weisse"
"Etta Matte"
"Eugene Gue"
"Eura Larue"
"Eva Dave"
"Eve Leve"
"Ewa Hawe"
"Ezra Marze"
"Fae Leaf"
"Flo Rolf"
"Flo Wolf"
"Flora Marolf"
"Florene Rolf"
"Gia Haig"
"Gil Lellig"
"Gina Hanig"
"Gino Honig"
"Gitte Rettig"
"Glenn Elg"
"Hal Olah"
"Harold Lorah"
"Helene Leh"
"Herb Reh"
"Hoyt Yoh"
"Ike Ueki"
"Ila Bali"
"Ileana Eli"
"Ilene Li"
"Ilona Noli"
"Ima Kawakami"
"Ina Kakani"
"Inga Bagni"
"Inga Magni"
"Inga Pagni"
"Inga Papagni"
"Iola Kaloi"
"Iola Loi"
"Iona Manoi"
"Ira Gari"
"Irena Neri"
"Irene Neri"
"Irene Veneri"
"Iva Ravi"
"Jade Dedaj"
"Jame Maj"
"Jamee Maj"
"Jani Kinaj"
"Ka Dudak"
"Kai Ziak"
"Kai Zuziak"
"Kala Balak"
"Kali Milak"
"Kamala Mak"
"Kami Kimak"
"Kami Mak"
"Kara Barak"
"Kari Jirak"
"Karisa Sirak"
"Karl Rak"
"Kate Tak"
"Katy Tak"
"Kay Babyak"
"Keely Leek"
"Keira Riek"
"Keli Bilek"
"Keli Cilek"
"Keli Lek"
"Kelle Sellek"
"Ken Okonek"
"Kena Danek"
"Kena Janek"
"Kena Vanek"
"Kena Yanek"
"Keri Sirek"
"Keva Pavek"
"Kia Haik"
"Kiana Naik"
"Kim Adamik"
"Kina Panik"
"King Nik"
"Kyla Halyk"
"Kyra Caryk"
"Lacy Cal"
"Lael Cleal"
"Lala Kalal"
"Lani Pinal"
"Lara Baral"
"Lavelle Val"
"Lavette Val"
"Lawanna Wal"
"Leda Nadel"
"Lee Keel"
"Lee Mcmeel"
"Lee Neel"
"Lee Peel"
"Leena Neel"
"Lenna Kannel"
"Leo Joel"
"Leona Noel"
"Leora Roel"
"Lera Karel"
"Lesa Basel"
"Lesia Maisel"
"Lessie Geissel"
"Lia Gail"
"Liana Nail"
"Liane Nail"
"Liberty Trebil"
"Lien Oneil"
"Lila Kalil"
"Lisa Basil"
"Lisa Vasil"
"Lise Sil"
"Lisette Sil"
"Lissa Bassil"
"Lita Patil"
"Liza Bazil"
"Lona Nol"
"Long Nol"
"Loni Nol"
"Lora Carol"
"Lory Tyrol"
"Love Devol"
"Lu Aul"
"Luann Aul"
"Luna Canul"
"Ma Eleam"
"Mamie Imam"
"Marcene Cram"
"Marci Cram"
"Marco Cram"
"Margene Gram"
"Margot Ogram"
"Mari Ram"
"Maria Bairam"
"Mark Akram"
"Marta Tram"
"Marty Tram"
"Mary Byram"
"Matt Tam"
"Maya Rayam"
"Maybelle Byam"
"Mel Klem"
"Melba Blem"
"Mika Kim"
"Mike Kim"
"Mila Lim"
"Mina Nim"
"Minh Nim"
"Mira Karim"
"Mirta Trim"
"Miyoko Yim"
"Na Gahagan"
"Na Gilligan"
"Na Henehan"
"Na Holohan"
"Na Noonan"
"Na Susan"
"Naida Hadian"
"Nam Dudman"
"Nan Onan"
"Nana Kanan"
"Naomi Moan"
"Ned Aden"
"Ned Dudden"
"Ned Eden"
"Ned Oden"
"Ned Rarden"
"Neda Baden"
"Neda Haden"
"Neda Vaden"
"Nedra Darden"
"Nedra Varden"
"Neely Leen"
"Neida Dien"
"Nella Gallen"
"Nella Mallen"
"Nelle Mcmellen"
"Nelle Yellen"
"Neoma Moen"
"Neomi Moen"
"Neta Paten"
"Nettie Leitten"
"Neva Haven"
"Nevada Daven"
"Nia Cain"
"Nia Fain"
"Nia Mcmain"
"Nia Pain"
"Nida Sadin"
"Nigel Klegin"
"Niki Aikin"
"Niki Kin"
"Nila Balin"
"Nilda Gadlin"
"Nilsa Gaslin"
"Nilsa Maslin"
"Nina Ganin"
"Nina Susanin"
"Nita Patin"
"Noemi Simeon"
"Nola Salon"
"Noma Damon"
"Nona Manon"
"Nora Aaron"
"Nora Baron"
"Nora Maron"
"Norah Aharon"
"Norah Aron"
"Norah Charon"
"Norah Sharon"
"Norene Ron"
"Nova Lavon"
"Nyla Lyn"
"Oda Bado"
"Odell Ledo"
"Odette Do"
"Ola Salo"
"Olene Lo"
"Ollie Aeillo"
"Oma Didamo"
"Omar Amo"
"Omer Emo"
"Omer Gremo"
"Ona Kano"
"Ona Llano"
"Onie Reino"
"Onita Patino"
"Onita Tino"
"Opal Apo"
"Ora Caro"
"Ora Faro"
"Ora Paparo"
"Oralee Laro"
"Oren Ero"
"Otis Ito"
"Pa Yap"
"Rae Gear"
"Raelene Lear"
"Ramiro Rimar"
"Ramon Omar"
"Ray Dyar"
"Rea Baer"
"Reba Faber"
"Reba Jaber"
"Reda Nader"
"Reda Sader"
"Reena Neer"
"Regan Ager"
"Regina Saniger"
"Regine Weniger"
"Reina Lanier"
"Reita Matier"
"Rema Hamer"
"Rena Waner"
"Renae Deaner"
"Renda Ladner"
"Rene Gener"
"Renea Haener"
"Renee Deener"
"Renita Tiner"
"Renna Danner"
"Renna Tanner"
"Ressie Weisser"
"Reta Yater"
"Retta Satter"
"Reva Baver"
"Rey Byer"
"Rey Dyer"
"Rey Iyer"
"Rhea Ehr"
"Rheba Behr"
"Ria Fair"
"Rima Jamir"
"Risa Nasir"
"Rod Amador"
"Rod Odor"
"Roger Gregor"
"Rolf Lor"
"Roman Amor"
"Romana Mor" [okdup]
"Ron Oconor"
"Roni Minor"
"Rosana Sor"
"Rose Sor"
"Roselle Sor"
"Rosita Tisor"
"Ross Sor"
"Rosy Sor"
"Rosy Tysor"
"Rubi Bur"
"Ruby Bur"
"Russ Sur"
"Ruth Tur"
"Sade Das"
"Sal Blas"
"Samara Mas"
"Sana Llanas"
"Sara Taras"
"Sarah Dharas"
"Sari Miras"
"Sari Ras"
"Selena Caneles"
"Selina Niles"
"Sena Vanes"
"Setsuko Kustes"
"Shawanna Wahs"
"Sim Amis"
"Sim Aramis"
"Sima Damis"
"Sina Mcmanis"
"Sirena Neris"
"Sol Abalos"
"Sol Avalos"
"Sona Danos"
"Sona Llanos"
"Soraya Ros"
"Su Titus"
"Sue Reus"
"Telma Hamlet"
"Tena Banet"
"Tena Llanet"
"Tera Jaret"
"Tera Maret"
"Tera Naret"
"Terra Barret"
"Terra Garret"
"Terra Jarret"
"Tessa Basset"
"Tessa Rasset"
"Tia Hait"
"Tim Smit"
"Toni Minot"
"Tracee Cart"
"Tressa Gassert"
"Tressie Weissert"
"Troy Ort"
"Wade Daw"
"Yetta Battey"
"Yetta Mattey"
"Yevette Vey"
"Yoko Koy"
"Yuki Kuy"
"Zaida Diaz"
"Zena Llanez"
"Zita Batiz"
"Zoe Oz"
"Zula Luz"

table of random palindrome lastfirst names
person-name
"Able, Melba"
"Adelizzi, Leda"
"Adels, Leda"
"Ader, Freda"
"Adle, Zelda"
"Adler, Elda"
"Adling, Nilda"
"Adner, Brenda"
"Adney, Enda"
"Ady, Lyda"
"Agle, Helga"
"Ahsan, Asha"
"Ahsing, Nisha"
"Aikins, Nikia"
"Ailes, Elia"
"Airola, Loria"
"Akima, Tamika"
"Akin, Anika"
"Alesi, Gisela"
"Ali, Cecila"
"Ali, Lila"
"Ali, Mila"
"Alice, Cecila"
"Alimo, Mila"
"Aline, Nila"
"Allen, Ella"
"Alley, Ella"
"Aloisi, Ola"
"Amell, Ema"
"Amill, Ima"
"Ammer, Emma"
"Amonette, Noma"
"Amons, Noma"
"Amoroso, Roma"
"Amory, Roma"
"Anand, Nana"
"Anast, Sana"
"Anawalt, Lawana"
"Anawaty, Tawana"
"Andel, Edna"
"Ander, Edna"
"Andes, Edna"
"Anelli, Willena"
"Anes, Ena"
"Anesi, Sena"
"Anez, Ena"
"Anidi, Dina"
"Anis, Ina"
"Arai, Kiara"
"Arakawa, Kara"
"Aramini, Mara"
"Arata, Tara"
"Arato, Tara"
"Ard, Isidra"
"Arden, Edra"
"Ardis, Isidra"
"Arevalo, Lavera"
"Ariaza, Ira"
"Arico, Cira"
"Arie, Keira"
"Arif, Ira"
"Arimoto, Mira"
"Aris, Ira"
"Armato, Tamra"
"Aroca, Cora"
"Aron, Elenora"
"Arone, Nora"
"Arons, Nora"
"Asif, Isa"
"Aslett, Elsa"
"Asley, Elsa"
"Ater, Greta"
"Aveni, Neva"
"Avenoso, Neva"
"Aver, Treva"
"Averette, Reva"
"Avery, Reva"
"Avie, Iva"
"Avis, Iva"
"Axel, Alexa"
"Bela, Caleb"
"Borg, Rob"
"Brehm, Herb"
"Camara, Mac"
"Camilli, Mac"
"Cassio, Issac"
"Darby, Brad"
"Datz, Tad"
"Deneen, Ed"
"Deneke, Ned"
"Deng, Ned"
"Depp, Ed"
"Dora, Jarod"
"Dorff, Rod"
"Dorn, Rod"
"Dornon, Rod"
"Dotolo, Tod"
"Drane, Lenard"
"Dua, Maud"
"Earl, Rae"
"Edie, Heide"
"Edu, Jude"
"Eid, Edie"
"Eisler, Elsie"
"Eisley, Elsie"
"Ekin, Ike"
"Eli, Cecile"
"Elia, Maile"
"Elleby, Belle"
"Ellena, Janelle"
"Ely, Kyle"
"Emore, Jerome"
"Eron, Elenore"
"Esler, Else"
"Etter, Everette"
"Gramm, Marg"
"Guo, Doug"
"Halik, Akilah"
"Halima, Kamilah"
"Hano, Jonah"
"Haro, Norah"
"Hnat, Anh"
"Hsi, Tish"
"Iburg, Rubi"
"Iller, Elli"
"Ilse, Lesli"
"Iman, Ami"
"Imoto, Tomi"
"Issacs, Cassi"
"Kral, Clark"
"Kramm, Mark"
"Lahr, Hal"
"Lama, Jamal"
"Laman, Amal"
"Lamarr, Amal"
"Lamm, Al"
"Laro, Coral"
"Larock, Coral"
"Laselle, Sal"
"Lavy, Val"
"Law, Al"
"Leban, Abel"
"Leban, Anabel"
"Ledo, Del"
"Lemelle, Mel"
"Leone, Noel"
"Leonette, Noel"
"Leong, Noel"
"Lerra, Darrel"
"Leuga, Raguel"
"Levra, Marvel"
"Leza, Hazel"
"Li, Cecil"
"Li, Gil"
"Lieng, Neil"
"Lim, Emil"
"Llera, Darell"
"Lorr, Errol"
"Losada, Sol"
"Losh, Sol"
"Lua, Raul"
"Maday, Adam"
"Mapp, Pam"
"Marban, Abram"
"Mari, Hiram"
"Mash, Sam"
"Mikasa, Kim"
"Mott, Tom"
"Muta, Tatum"
"Naidoo, Dian"
"Naidu, Dian"
"Naik, Ian"
"Nail, Lillian"
"Naill, Ian"
"Nair, Brian"
"Naji, Jan"
"Nall, Ellan"
"Namur, Truman"
"Nau, Juan"
"Navarra, Van"
"Navin, Ivan"
"Nay, Ryan"
"Neel, Ileen"
"Nell, Allen"
"Neller, Ellen"
"Nero, Loren"
"Neve, Keven"
"Niles, Elin"
"No, Son"
"Noda, Don"
"Noe, Deon"
"Noh, Shon"
"Nojiri, Jon"
"Nola, Lon"
"Noll, Lon"
"Nolt, Lon"
"Nord, Ron"
"Notley, Elton"
"Novel, Evon"
"Novell, Evon"
"Nuse, Sun"
"Nush, Sun"
"Nybo, Robyn"
"Obama, Bo"
"Ord, Isidro"
"Osawa, So"
"Ott, Otto"
"Pike, Kip"
"Rama, Jamar"
"Rama, Lamar"
"Rama, Tamar"
"Ramos, Omar"
"Rase, Cesar"
"Rebman, Amber"
"Reh, Cher"
"Remley, Elmer"
"Remo, Homer"
"Remos, Omer"
"Reys, Yer"
"Rial, Blair"
"Rolff, Flor"
"Rona, Eleanor"
"Rover, Trevor"
"Sailer, Elias"
"Sallade, Dallas"
"Samo, Tomas"
"Sano, Jonas"
"Sele, Les"
"Self, Les"
"Selz, Les"
"Seng, Agnes"
"Seniff, Ines"
"Sidor, Odis"
"Siller, Ellis"
"Sina, Janis"
"Sircy, Cris"
"Sirin, Iris"
"Sirko, Kris"
"Siu, Luis"
"Siva, Davis"
"Siva, Mavis"
"Sivak, Avis"
"Sival, Avis"
"Sivan, Avis"
"Sivley, Elvis"
"Soman, Amos"
"Su, Gus"
"Sugiki, Gus"
"Sung, Agnus"
"Tapaha, Pat"
"Tena, Janet"
"Todd, Dot"
"Trass, Art"
"Traut, Stuart"
"Truby, Burt"
"Truka, Kurt"
"Tyo, Hoyt"
"Yamada, May"
"Yeo, Joey"
"Yero, Corey"
"Yerty, Trey"
"Yore, Leroy"
"York, Roy"
"Yu, Guy"
"Zapata, Paz"
"Zill, Liz"

chapter random businesses

table of businesses
biz-name
"Colby Bloc"
"Dairy Myriad"
"Derby Bred"
"Layaway Al"
"Looks Skool"
"Rife Kefir"
"Skooby Books"
"Tru-Go Yogurt"
"We Sew"

volume random responses

part the code

to next-rand (t - a table name):
	choose row with tabnam of t in table of all randoms;
	increment tabidx entry;
	if tabidx entry > number of rows in tabnam entry:
		if debug-state is true, say "(Cycling) ";
		now tabidx entry is 1;
		if thru-yet entry is 0:
			now thru-yet entry is 1;
			now rand-cycle is true;
	let Q be tabidx entry;
	let lb be lbrk entry;
	choose row Q in tabnam entry;
	say "[randtxt entry][if lb is true][line break][else][no line break][end if]";

to say next-rand-txt of (t - a table name):
	next-rand t;

table of all randoms
tabnam	tabidx	thru-yet	lbrk	desc	cycle-note
table of altbooks	0	0	false	"extra books in the Tract Cart"	"You've read all the books on the tract cart. Hooray for curiosity!"
table of attackings	0	0	true	"responses to ATTACK"	--
table of Bond Nob bars	0	0	false	"bars the Bond Nob visits"	-- [?? may cause a problem cycling talking to nob]
table of burnies	0	0	true	"responses to BURN"	--
table of diktat taunts	0	0	false	"Diktat Kid taunts"	--
table of Moo Room animals	0	0	true	"Moo Room animals (LISTEN)"	--
table of My Gym songs	0	0	false	"songs in My Gym (LISTEN)"	--
table of noesies	0	0	true	"responses to NO"	--
table of nothings	0	0	true	"responses to empty commands"	--
table of rejected sidekicks	0	0	false	"the Diktat Kid's rejected sidekicks"	--
table of Rob droning	0	0	false	"things Rob babbles about"	--
table of singstuff	0	0	true	"responses to SINGing"	--
table of snooty toon ads	0	0	true	"snooty toons ads"	--
table of swearstuff	0	0	true	"responses to SWEARing"	--
table of undoings	0	0	true	"UNDOing notifications"	--
table of waittxt	0	0	true	"responses to WAITing"	--
table of wordy drow laments	0	0	false	"Wordy Drow laments"	--
table of yessies	0	0	true	"responses to YES"	--
table of yuge taunts	0	0	true	"Yuge Guy taunts"	"Señor drones, you think you yourself, as the Yuge Guy winds up for another round of nonsense."

rand-cycle is a truth state that varies.

every turn (this is the notify cycling rule):
	if rand-cycle is true:
		let tn be a table-name;
		let tables-found be 0;
		now rand-cycle is false;
		repeat through table of all randoms:
			if thru-yet entry is 1:
				now thru-yet entry is 2;
				increment tables-found;
				if tables-found is 1:
					say "[if there is a cycle-note entry][cycle-note entry][else]You have cycled all the available random responses for an action or NPC's babble.[end if]";
				else if tables-found is 2:
					say "This is a further note to say you've done so more than once this turn, which is an impressive bit of timing, even if it doesn't get you any points.";
		if tables-found is 0 and debug-state is true, say "This is a BUG--you should be notified of cycling.";
		the rule succeeds;

section debugs

chapter troing

troing is an action out of world.

understand the command "tro" as something new.

understand "tro" as troing.

carry out troing:
	repeat through table of all randoms:
		say "[tabnam entry] has [number of rows in tabnam entry] rows.";
	the rule succeeds;

part the tables

[arranged alphabetically]

table of altbooks
randtxt
"Ares's Era"
"D'oh, Serene, Reshod"
"D'oh, Temp Method"
"Dad, Dad"
"Dew Onuses Unowed"
"Dew, Awed"
"Dew, Owed"
"Dib [']Nuff Unbid"
"Die, Rended Nereid"
"Dif, Firth Triffid"
"Dig ruts? Turgid"
"Dim Anon Amid"
"Dip Such, Cuspid"
"Dip, Arc, Rapid"
"Dip, Ill Lipid"
"Do Banana Bod"
"Do Bozo Bod"
"Do Brewer Bod"
"Do Cede, Cod"
"Do Coo, Cod"
"Do Pacific a Pod"
"Do Pay a Pod"
"Do, Gamma God"
"Don Represser Pernod"
"Due Spy Pseud"
"Duo-Ladened Aloud"
"Eat, Roam, Aortae"
"Ebb, Acidic Abbe"
"Ebb, Error Rebbe"
"Emacs Came"
"Eponymy? Nope"
"Gigolo Gig"
"If I Had a Hi-Fi"
"A Mardy Drama"
"Me, Lo, Golem"
"Miss a Passim"
"Mo['] Idiom"
"Mr. Owl Worm"
"My Nonacidic Anonym"
"Neil's Lien"
"O Bonobo"
"Otter Amaretto"
"Rise Aesir"
"Risk Sir"
"Satire Veritas"
"Solo Gigolos"
"Sore Heros"
"Sore Zeros"
"Torsos, ROT"
"We Few"
"Wedded Dew"
"Yo Banana Boy"
"Zot: A to Z"

table of attackings
randtxt
"D00d!"
"Dude! Dud."
"Goon! Oog!"
"Harm! Rah!"
"Hood! Ooh!"
"Hurt! Ruh!"
"Knock! Conk!"
"Nae mean."
"Ole! Lo!"
"Pah! Whap?"
"Pal, SLAP?!"
"Po['] bop!"
"Pop!"
"Pow-op! Pow-op!"
"Regard, rager!"
"Spar? Traps!"
"Spare raps!"
"Tiff. Fit."
"To ire! Riot!"
"Tonk? Not."
"Ye KO? Pokey!"
"Yob! Boy."

table of burnies
randtxt
"Burn! Rub!"
"Igniting, I!"
"Rah! Char!"

table of Bond Nob bars
randtxt
"Bar Crab"
"Brewer B"
"Met [']Em"
"MRA Farm"
"Nigh Gin"
"Pat's Tap"
"Pub UP"
"Sara's"
"Scene C's"
"Senor One's"
"Soho's"
"Soto's"
"Spike-Kip's"
"Tipsy Spit"
"Tope Depot"
"Zara'Z"
"Zorro'z"
"Zuzu'Z"

[this may be related to Yuge Guy taunts, but the Diktat Kid insults you. The Yuge Guy puffs himself up.]
table of diktat taunts
randtxt
"Da bad! Da BAD!! DA BAD!!!"
"Dire! Rid!"
"Dude(tte)! Dud!"
"Duh, THUD!"
"Mess [']em!"
"Noose soon!"
"Peewee, weep!"
"Poorer! Oop!"
"Rah! Thar!"
"Resoldered loser!"
"Rofl! For..."
"A tarred errata!"
"ZAP, spaz!"

table of Moo Room animals
randtxt
"an un-gnu"
"a buck cub"
"a rat avatar"
"sab mambas"
"sewer ewes"
"ska yaks"
"smart rams"
"sum emus"
"a tart rat"

table of My Gym songs
randtxt
"[']Allo, Dolla[']"
"All Illa[']"
"Do Mo['] Mod"
"Emote to Me"
"Hat-stah"
"Hook, Ooh"
"Kazoo Zak"
"Krew Twerk"
"Le BE Rebel"
"Major Pro Jam"
"Me: Opt, Poem"
"O, Got to Go"
"O/T: Teh Ghetto"
"Ode: Dude, DO"
"Opera Repo"
"Rap Spar"
"See Lee's"
"Set-a-Dates"
"Set-a-Mates"
"Sum Us"
"Sun on Us"
"To Own: WOOT"
"We Nab Anew"
"Yet a Matey"
"Yo, Beer Free, Boy"
"YOLO'y"

table of noesies
randtxt
"Dash sad."
"Derided! Ired!"
"Emo, me."
"EVAR Grave?"
"Hm. SMH."
"Moody? Doom!"
"No way? Aw, ON!"
"One no."
"Oo! Noo!"
"Poor droop."
"Stone NOTs."
"Woe meow."
"Ye po['] mopey!"
"Ye Po['] Nopey."

table of nothings
randtxt
"Drown, word!"
"Dud!"
"Eh, the..."
"Hey! Eh?"
"It? Nah, anti."
"Line? Nil."
"Meh. Ahem!"
"Minim..."
"Mum?"
"No peep on?"
"Peep?!"
"POST, sop!"
"Spill, lips!"
"Sue Zeus?!"
"Too moot."
"Verb! Rev!"
"Ya, no! Nay!"
"Yo! Coy?"

table of rejected sidekicks
randtxt
"Able Melba"
"Ammo Momma"
"ASAP Asa"
"Emil Slime"
"Evil Clive"
"Gory Rog"
"Iller Elli"
"Mad Adam"
"Obese Bo"
"Wolf Low"

table of Rob droning
randtxt
"[']Tis. Suss it!"
"Boone?! Noob!"
"EOF, Foe!"
"If I wifi..."
"More ROM!"
"Piece IP?!"
"Posts-op? POST, sop!"
"Prove VORP!"
"Resume [']m, user!"
"SETI sites!"
"Signing is..."
"Spidered IPs?!"
"Y-array?!"

table of singstuff
randtxt
"Ode? Redo!"
"Rock! Cor!"
"Tone? Not!"
"Tune nut!"
"Yodeled? Oy!"

table of snooty toon ads
randtxt
"Ay, a papaya"
"Food ... oof"
"No revile-liver on"
"Nom la salmon"
"Risotto, Sir"
"Salad (alas)"
"Sup Opus"

[?? tafl.py sort so parentheses as well as a/an/the don't affect alphabetization]
table of swearstuff
randtxt
"(R)rude! Dur(r)!"
"Bad? A dab!"
"Dammit, I'm mad!"
"Dark. Rad!"
"Delivery: reviled!"
"Guff! Ug!"
"Hell, eh?"
"Hoot! Ooh!"
"Hot! Oh!"
"Kook!"
"Not on!"
"Pah, chap!"
"Redder... redder..."
"Rep me, temper!"
"Speel? Bleeps."
"Tact, cat!"
"Tic? Illicit."
"Tit!"
"Tut!"
"Ward raw..."
"We mew!"
"Well, EW!"
"Y'booby!"
"Y'kooky?"
"Yap? Ay!"

table of undoings
randtxt
"'Redo-coder! Redo-coder!'"
"[']S poor. Oops!"
"Ay, CYA."
"Did. [']Nuff? Undid."
"Did. Error? Redid."
"Eff a gaffe."
"Nixin[']..."
"Or, Perp, REPRO!"
"Pah, simp! Mishap!"
"Sod [']er! Redos!"
"Time: remit."

table of waittxt
randtxt
"Camp, mac!"
"Deed, deed, deed!"
"Def['] faffed!"
"Do, STAT, sod!"
"Don't nod!"
"Gall! Lag!"
"GO, dog!"
"A lag gala!"
"Mull! Um..."
"Nix ALERT. Relaxin[']!"
"No gig on?"
"Now? On!"
"Pal...flap!"
"Panic? I nap!"
"Pas ASAP!"
"A rests era!"
"Resume, muser!" [okdup]
"Rev, O Rover!"
"Sod dos."
"Stare? Rats!"
"Stir! It's..."
"Task: SAT!"
"Truce, curt."
"Wait! I ... aw ..."
"Wandered? Naw."
"We nap anew."
"Won't, Now."
"Y'revery!"
"Yon! Oy!"

table of wordy drow laments
randtxt
"Deity...tied!"
"Die, id!"
"Ebb? Be!"
"Eh, Tithe!"
"Guts, TUG!"
"Id-egged, I"
"No Sin is On!"
"Onan? A no!"
"Sad as..."
"Sob! Mild Limbos!"
"Sog, Ebb, Egos!"
"Want? Naw!"

table of yessies
randtxt
"Hosannas, Oh!"
"Laud-ual!"
"Nod on!"
"Ooh, aye! Yahoo!"
"Pep!"
"Pip, pip!"
"Plus? Ulp."
"Too woot!"
"Wahoo! Haw!"
"Yay!"

table of yuge taunts
randtxt
"A-lists? I? La!"
"Ahahahahahaha!"
"Ey, dye?!"
"Gibe! Big!"
"Hog, oh!"
"Huge! Guh!"
"I B FBI!"
"Iz no Ponzi!"
"KJU? J/k!"
"Main, I am!"
"ME!!!! Haw. Ahem."
"Me: sees [']em!"
"Misdeeds? I'm ..."
"Name: HE-MAN!"
"Nem O['] women!"
"Nil Appalin[']!"
"Null [']un!"
"Odd-*** Saddo!" [ignore]
"Oh, BHO!"
"Ooh...shoo!"
"Pal! Clap!"
"Pal, rub burlap!"
"A papa! A papa!"
"Re-sold LOSER!"
"ROB ALL LABOR!"
"Rug?! Ur..."
"So-sos!"
"Soros! Soros!"
"Sue Me?! Us?!"
"Wane? Naw!"
"Y'r Dry!"
"You! Oy!"

Ailihphilia Tables ends here.

---- DOCUMENTATION ----
