Version 1/171220 of Put It Up Tables by Andrew Schultz begins here.

volume random names of people and places

[use dbh.py to generate debug table version of this file]

chapter random names

[NOTE: can-m + can-f = a unisex name. False/False should never happen.]
table of random authors
person-name	can-m	can-f
"Eliza Bazile"	false	true
"Kera Marek"	false	true
"Leta Patel"	false	true
"Mika Hakim"	false	true
"Norma Damron"	false	true
"Reiko Kier"	false	true
"Rhea Baehr"	false	true
"Blake DeKalb"	true	true
"Leigh Giel"	true	true
"Adam Imada"	true	false
"Eldon Odle"	true	false
"Emory Rome"	true	false
"Gino Konig"	true	false
"Levi Rivel"	true	false
"Mark Cockram"	true	false
"Neil Klien"	true	false

table of random palindrome names
person-name
"Abe Keba"
"Agnus Unga"
"Alena Panela"
"Ali Vila"
"Alina Manila"
"Alona Zanola"
"Ami Cima"
"Amy Ma"
"Anika Kina"
"Anitra Martina"
"Annalee Lanna"
"Anne Kenna"
["Annika Kinna"
"Anya Rayna"
"Asa Casa"
"Ava Lava"
"Azalee Laza"
"Bernie Weinreb"
"Bert Streb"
"Betsey Esteb"
"Blake Kalb"
"Breana Erb"
"Breanna Erb"
"Bret Erb"
"Bruce Curb"
"Burt Strub"
"Cami Mac"
"Cassie Issac"
"Daisy Siad"
"Dara Jarad"
"Darby Brad"
"Dee Reed"
"Denese Ned"
"Dian Aid"
"Diann Aid"
"Dorene Rod"
"Dori Girod"
"Duane Renaud"
"Ed Larralde"
"Ed Lazalde"
"Edie Weide"
"Edna Lalande"
"Edra Garde"
"Ela Bale"
"Ela Cicale"
"Ela Dale"
"Ela Yale"
"Elana Canale"
"Elda Wadle"
"Eldon Odle"
"Eli Kile"
"Elias Osaile"
"Elida Nadile"
"Elisa Basile"
"Eliza Bazile"
"Ella Malle"
"Ellena Fanelle"
"Elli Tille"
"Elly Hylle"
"Elsie Isle"
"Elva Mavle"
"Emiko Kime"
"Emil Glime"
"Emily Lime"
"Emma Hamme"
"Emmitt Imme"
"Emmitt Timme"
"Emory Rome"
"Ena Lane"
"Ena Sayasane"
"Enoch Cone"
"Enola Malone"
"Essie Heisse"
"Essie Weisse"
"Etta Matte"
"Eugene Gue"
"Eura Larue"
"Eva Dave"
"Eve Leve"
"Ewa Hawe"
"Ezra Marze"
"Fae Leaf"
"Flo Rolf"
"Flo Wolf"
"Flora Marolf"
"Florene Rolf"
"Gia Haig"
"Gil Lellig"
"Gino Honig"
"Gino Konig"
"Glenn Elg"
"Hal Olah"
"Harold Lorah"
"Helene Leh"
"Herb Reh"
"Hoyt Yoh"
"Ike Ueki"
"Ila Bali"
"Ileana Eli"
"Ilene Li"
"Ilona Noli"
"Ima Kawakami"
"Ina Kakani"
"Inga Bagni"
"Inga Magni"
"Inga Pagni"
"Inga Papagni"
"Iola Kaloi"
"Iola Loi"
"Iona Manoi"
"Ira Gari"
"Irena Neri"
"Irene Neri"
"Irene Veneri"
"Iva Ravi"
"Jade Dedaj"
"Jame Maj"
"Jamee Maj"
"Jani Kinaj"
"Ka Dudak"
"Kai Ziak"
"Kai Zuziak"
"Kala Balak"
"Kali Milak"
"Kamala Mak"
"Kami Kimak"
"Kami Mak"
"Kara Barak"
"Kari Jirak"
"Karisa Sirak"
"Karl Rak"
"Kate Tak"
"Katy Tak"
"Kay Babyak"
"Keely Leek"
"Keira Riek"
"Keli Bilek"
"Keli Cilek"
"Keli Lek"
"Kelle Sellek"
"Ken Okonek"
"Kena Danek"
"Kena Janek"
"Kena Vanek"
"Kena Yanek"
"Kera Marek"
"Keri Sirek"
"Keva Pavek"
"Kia Haik"
"Kiana Naik"
"Kim Adamik"
"Kina Panik"
"King Nik"
"Kyla Halyk"
"Kyra Caryk"
"Lacy Cal"
"Lael Cleal"
"Lala Kalal"
"Lani Pinal"
"Lara Baral"
"Lavelle Val"
"Lavette Val"
"Lawanna Wal"
"Leda Nadel"
"Lee Keel"
"Lee Mcmeel"
"Lee Neel"
"Lee Peel"
"Leena Neel"
"Leigh Giel"
"Lenna Kannel"
"Leo Joel"
"Leona Noel"
"Leora Roel"
"Lera Karel"
"Lesa Basel"
"Lesia Maisel"
"Lessie Geissel"
"Li Cecil"
"Lia Gail"
"Liana Nail"
"Liane Nail"
"Liberty Trebil"
"Lien Oneil"
"Lila Kalil"
"Lisa Basil"
"Lisa Vasil"
"Lise Sil"
"Lisette Sil"
"Lissa Bassil"
"Lita Patil"
"Liza Bazil"
"Lona Nol"
"Long Nol"
"Loni Nol"
"Lora Carol"
"Lory Tyrol"
"Love Devol"
"Lu Aul"
"Luann Aul"
"Luna Canul"
"Ma Eleam"
"Mamie Imam"
"Marcene Cram"
"Marci Cram"
"Marco Cram"
"Margene Gram"
"Margot Ogram"
"Mari Ram"
"Maria Bairam"
"Mark Akram"
"Mark Cockram"
"Marta Tram"
"Marty Tram"
"Mary Byram"
"Maya Rayam"
"Maybelle Byam"
"Mel Klem"
"Melba Blem"
"Mika Hakim"
"Mika Kim"
"Mike Kim"
"Mila Lim"
"Mina Nim"
"Minh Nim"
"Mira Karim"
"Mirta Trim"
"Miyoko Yim"
"Na Gahagan"
"Na Gilligan"
"Na Henehan"
"Na Holohan"
"Na Noonan"
"Na Susan"
"Naida Hadian"
"Nam Dudman"
"Nan Onan"
"Nana Kanan"
"Naomi Moan"
"Ned Aden"
"Ned Dudden"
"Ned Eden"
"Ned Oden"
"Ned Rarden"
"Neda Baden"
"Neda Haden"
"Neda Vaden"
"Nedra Darden"
"Nedra Varden"
"Neely Leen"
"Neida Dien"
"Neil Klien"
"Nella Gallen"
"Nella Mallen"
"Nelle Mcmellen"
"Nelle Yellen"
"Neoma Moen"
"Neomi Moen"
"Neta Paten"
"Nettie Leitten"
"Neva Haven"
"Nevada Daven"
"Nia Cain"
"Nia Fain"
"Nia Mcmain"
"Nia Pain"
"Nida Sadin"
"Nigel Klegin"
"Niki Aikin"
"Niki Kin"
"Nila Balin"
"Nilda Gadlin"
"Nilsa Gaslin"
"Nilsa Maslin"
"Nina Ganin"
"Nina Susanin"
"Nita Patin"
"Noe Deon"
"Noemi Simeon"
"Nola Salon"
"Noma Damon"
"Nona Manon"
"Nora Aaron"
"Nora Baron"
"Nora Maron"
"Norah Aharon"
"Norah Aron"
"Norah Charon"
"Norah Sharon"
"Norene Ron"
"Norma Damron"
"Nova Lavon"
"Nyla Lyn"
"Oda Bado"
"Odell Ledo"
"Odette Do"
"Ola Salo"
"Olene Lo"
"Ollie Aeillo"
"Oma Didamo"
"Omar Amo"
"Omer Emo"
"Omer Gremo"
"Ona Kano"
"Ona Llano"
"Onie Reino"
"Onita Patino"
"Onita Tino"
"Opal Apo"
"Ora Caro"
"Ora Faro"
"Ora Paparo"
"Oralee Laro"
"Oren Ero"
"Otis Ito"
"Pa Yap"
"Rae Gear"
"Raelene Lear"
"Ramiro Rimar"
"Ramon Omar"
"Ray Dyar"
"Rea Baer"
"Reba Faber"
"Reba Jaber"
"Reda Nader"
"Reda Sader"
"Reena Neer"
"Regan Ager"
"Regina Saniger"
"Regine Weniger"
"Reiko Kier"
"Reina Lanier"
"Reita Matier"
"Rema Hamer"
"Rena Waner"
"Renae Deaner"
"Renda Ladner"
"Rene Gener"
"Renea Haener"
"Renee Deener"
"Renita Tiner"
"Renna Danner"
"Renna Tanner"
"Ressie Weisser"
"Reta Yater"
"Retta Satter"
"Reva Baver"
"Rey Byer"
"Rey Dyer"
"Rey Iyer"
"Rhea Baehr"
"Rhea Ehr"
"Rheba Behr"
"Ria Fair"
"Rima Jamir"
"Risa Nasir"
"Rod Amador"
"Rod Odor"
"Roger Gregor"
"Rolf Lor"
"Roman Amor"
"Romana Mor"
"Ron Oconor"
"Roni Minor"
"Rosana Sor"
"Rose Sor"
"Roselle Sor"
"Rosita Tisor"
"Ross Sor"
"Rosy Sor"
"Rosy Tysor"
"Rubi Bur"
"Ruby Bur"
"Russ Sur"
"Ruth Tur"
"Sade Das"
"Sal Blas"
"Samara Mas"
"Sana Llanas"
"Sara Taras"
"Sarah Dharas"
"Sari Miras"
"Sari Ras"
"Selena Caneles"
"Selina Niles"
"Sena Vanes"
"Setsuko Kustes"
"Shawanna Wahs"
"Sima Damis"
"Sina Mcmanis"
"Sirena Neris"
"Sol Abalos"
"Sol Avalos"
"Sona Danos"
"Sona Llanos"
"Soraya Ros"
"Su Titus"
"Sue Reus"
"Telma Hamlet"
"Tena Banet"
"Tena Llanet"
"Tera Jaret"
"Tera Maret"
"Tera Naret"
"Terra Barret"
"Terra Garret"
"Terra Jarret"
"Tessa Basset"
"Tessa Rasset"
"Tia Hait"
"Tim Smit"
"Toni Minot"
"Tracee Cart"
"Tressa Gassert"
"Tressie Weissert"
"Troy Ort"
"Wade Daw"
"Yetta Battey"
"Yetta Mattey"
"Yevette Vey"
"Yoko Koy"
"Yuki Kuy"
"Zaida Diaz"
"Zena Llanez"
"Zita Batiz"
"Zoe Oz"
"Zula Luz"]

chapter random businesses

table of businesses
biz-name
"Dairy Myriad"
"Derby Bred"
"Layaway Al"
"Looks Skool"
"Rife Kefir"
"Skooby Books"

volume random responses

part the code

to next-rand (t - a table name):
	choose row with tabnam of t in table of all randoms;
	increment tabidx entry;
	if debug-state is true and tabidx entry > number of rows in tabnam entry:
		say "(Cycling) ";
		now tabidx entry is 1;
	let Q be tabidx entry;
	let lb be lbrk entry;
	choose row Q in tabnam entry;
	say "[randtxt entry][if lb is true][line break][end if][else][run paragraph on][end if]";

table of all randoms
tabnam	tabidx	lbrk	desc
table of altbooks	0	false	"extra books in the Tract Cart"
table of attackings	0	true	"responses to ATTACK"
table of burnies	0	true	"responses to BURN"
table of diktat taunts	0	true	"Diktat Kid taunts"
table of My Gym songs	0	false	"songs in My Gym (LISTEN)"
table of noesies	0	true	"responses to NO"
table of nothings	0	true	"responses to empty commands"
table of singstuff	0	true	"responses to SINGing"
table of swearstuff	0	true	"responses to SWEARing"
table of undoings	0	true	"UNDOing notifications"
table of waittxt	0	true	"responses to WAITing"
table of yessies	0	true	"responses to YES"
table of yuge taunts	0	true	"Yuge Guy taunts"

part the tables

[arranged alphabetically]

table of altbooks
randtxt
"D'oh, Serene, Reshod"
"D'oh, Temp Method"
"Dew Onuses Unowed"
"Dew, Awed"
"Dew, Owed"
"Dib [']Nuff Unbid"
"Die, Rended Nereid"
"Dif, Firth Triffid"
"Dig ruts? Turgid"
"Dim Anon Amid"
"Dip Such, Cuspid"
"Dip, Arc, Rapid"
"Dip, Ill Lipid"
"Do Banana Bod"
"Do Bozo Bod"
"Do Brewer Bod"
"Do Cede, Cod"
"Do Coo, Cod"
"Do Pacific a Pod"
"Do Pay a Pod"
"Do, Gamma God"
"Don Represser Pernod"
"Due Spy Pseud"
"Duo-Ladened Aloud"
"Eat, Roam, Aortae"
"Ebb, Acidic Abbe"
"Ebb, Error Rebbe"
"Emacs Came"
"Eponymy? Nope"
"Gigolo Gig"
"If I Had a Hi-Fi"
"A Mardy Drama"
"Mo['] Idiom"
"More ROM"
"Mr. Owl Worm"
"Otter Amaretto"
"Rise Aesir"
"Risk Sir"
"Solo Gigolos"
"Sore Heros"
"Sore Zeros"
"Torsos, ROT"
"We Few"
"Wedded Dew"
"Yo Banana Boy"

table of attackings
randtxt
"D00d!"
"Dude! Dud."
"Harm! Rah!"
"Hood! Ooh!"
"Hurt! Ruh!"
"Knock! Conk!"
"Nae mean."
"Ole! Lo!"
"Pah! Whap?"
"Pal, SLAP?!"
"Po['] bop!"
"Pop!"
"Pow-op! Pow-op!"
"Spare raps!"
"Tiff. Fit."
"Tonk? Not."
"Ye KO? Pokey!"
"Yob! Boy."

table of burnies
randtxt
"Burn! Rub!"
"Igniting, I!"
"Rah! Char!"

[the Diktat Kid insults you. The Yuge Guy puffs himself up.]
table of diktat taunts
randtxt
"Dire! Rid!"
"Dude(tte)! Dud!"
"Duh, THUD!"
"Mess [']em!"
"Noose soon!"
"Peewee, weep!"
"Poorer! Oop!"
"Rah! Thar!"
"Resoldered loser!"
"Rofl! For..."
"A tarred errata!"
"ZAP, spaz!"

table of My Gym songs
randtxt
"Kazoo Zak"
"Krew Twerk"
"O/T: Teh Ghetto"
"Opera Repo"
"Rap Spar"
"Yo, Beer Free, Boy"

table of noesies
randtxt
"Dash sad."
"Derided! Ired!"
"Emo, me."
"Hm. SMH."
"Moody? Doom!"
"No way? Aw, ON!"
"One no."
"Oo! Noo!"
"Poor droop."
"Stone NOTs."
"Woe meow."
"Ye Po['] Nopey."

table of nothings
randtxt
"Drown, word!"
"Dud!"
"Eh, the..."
"Hey! Eh?"
"It? Nah, anti."
"Line? Nil."
"Meh. Ahem!"
"Mum?"
"No peep on?"
"Peep?!"
"POST, sop!"
"Spill, lips!"
"Too moot."
"Verb! Rev!"
"Verb! Rev!"
"Ya, no! Nay!"
"Yo! Coy?"

table of singstuff
randtxt
"Ode? Redo!"
"Rock! Cor!"
"Tone? Not!"
"Tune nut!"
"Yodeled? Oy!"

[?? tafl.pl sort so parentheses as well as a/an/the don't affect alphabetization]
table of swearstuff
randtxt
"(R)rude! Dur(r)!"
"Bad? A dab!"
"Dammit, I'm mad!"
"Dark. Rad!"
"Guff! Ug!"
"Hell, eh?"
"Hoot! Ooh!"
"Hot! Oh!"
"Kook!"
"Not on!"
"Pah, chap!"
"Redder... redder..."
"Rep me, temper!"
"Speel? Bleeps."
"Tact, cat!"
"Tic? Illicit."
"Tit!"
"Tut!"
"Ward raw..."
"We mew!"
"Well, EW!"
"Y'booby!"
"Y'kooky?"
"Yap? Ay!"

table of undoings
randtxt
"'Redo-coder! Redo-coder!'"
"[']S poor. Oops!"
"Did. [']Nuff? Undid."
"Did. Error? Redid."
"Eff a gaffe."
"Nixin[']..."
"Or, Perp, REPRO!"
"Pah, simp! Mishap!"
"Time: remit."

table of waittxt
randtxt
"Camp, mac!"
"Deed, deed, deed!"
"Def['] faffed!"
"Do, STAT, sod!"
"Don't nod!"
"Gall! Lag!"
"GO, dog!"
"A lag gala!"
"Mull! Um..."
"No gig on?"
"Now? On!"
"Pal...flap!"
"Panic? I nap!"
"A rests era!"
"Resume, muser!"
"Rev, O Rover!"
"Sod dos."
"Stare? Rats!"
"Stir! It's..."
"Truce, curt."
"Wait! I ... aw ..."
"Wandered? Naw."
"Won't, Now."

table of wordy drow laments
randtxt
"'Deity...tied!'"
"'Die, id!'"
"'Eh, Tithe!'"
"'No Sin is On!'"

table of yessies
randtxt
"Hosannas, Oh!"
"Laud-ual!"
"Nod on!"
"Ooh, aye! Yahoo!"
"Pep!"
"Pip, pip!"
"Plus? Ulp."
"Too woot!"
"Wahoo! Haw!"
"Yay!"

table of yuge taunts
randtxt
"Ahahahahahaha!"
"Gibe! Big!"
"Hog, oh!"
"Huge! Guh!"
"Main, I am!"
"ME!!!! Haw. Ahem."
"Me: sees [']em!"
"Misdeeds? I'm ..."
"Name: HE-MAN!"
"Nem O['] women!"
"Null [']un!"
"Odd-*** Saddo!" [ignore]
"Ooh...shoo!"
"Pal! Clap!"
"Pal, rub burlap!"
"A papa! A papa!"
"Soros! Soros!"
"Wane? Naw!"
"You! Oy!"

Put It Up Tables ends here.

---- DOCUMENTATION ----
